DEBUG:root:form=2
ERROR:django.request:Internal Server Error: /cardapio/pizza/edit/2
Traceback (most recent call last):
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\igoro\OneDrive\Documentos\GitHub\infoPizza\infopizza\app\views.py", line 54, in cardapioPizzaUpdate
    return render(request, 'cardapio/pizza/edit.html', {'form':form,'form2':form2})
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 696, in __init__
    filter_func = parser.find_filter(filter_name)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'pizza'
ERROR:django.request:Internal Server Error: /cardapio/pizza/edit/2
Traceback (most recent call last):
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'pizza'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 881, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'pizza'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'pizza'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\igoro\OneDrive\Documentos\GitHub\infoPizza\infopizza\app\views.py", line 54, in cardapioPizzaUpdate
    return render(request, 'cardapio/pizza/edit.html', {'form':form,'form2':form2})
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 733, in resolve
    arg_vals.append(arg.resolve(context))
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\igoro\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [pizza] in [{'True': True, 'False': False, 'None': None}, {}, {}, {'form': <ItemForm bound=False, valid=Unknown, fields=(cat;nome;desc)>, 'form2': <django.forms.formsets.ItemInfoFormFormSet object at 0x00000194F4E75180>}]
INFO:django.utils.autoreload:C:\Users\igoro\OneDrive\Documentos\GitHub\infoPizza\infoPizza\app\views.py changed, reloading.
DEBUG:root:form=2
DEBUG:root:form=2
DEBUG:root:form=1
